In [10]:
import torch




In [11]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [12]:
print(scalar.ndim)
# Get the Python number within a tensor (only works with one-element tensors)
print(scalar.item())


0
7


In [13]:
# Vector
vector = torch.tensor([10, 20, 30, 40, 50])
vector

tensor([10, 20, 30, 40, 50])

In [26]:
matrix= torch.tensor([[0,0,0],[0,0,0],[0,0,0]])
zeros= torch.zeros(size=(3,3))
matrix,zeros

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [20]:
matrix2= torch.tensor([[1,1,1,1,1],[1,1,1,1,1]])
matrix2

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [24]:
matrix3= torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
# Create a tensor of all ones
ones = torch.ones(size=(4 ,4))
ones, ones.dtype
matrix3,ones

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [23]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1749, 0.8742, 0.9896, 0.4672],
         [0.9454, 0.1487, 0.1308, 0.2262],
         [0.7511, 0.5658, 0.4381, 0.8803]]),
 torch.float32)

In [31]:
random_tensor = torch.rand(size=(5, 5))
random_tensor.shape,random_tensor.dtype, random_tensor.device


(torch.Size([5, 5]), torch.float32, device(type='cpu'))

In [43]:
zero= torch.tensor([0,0,0])
print(zero.dtype)
#1st way
print(zero.float())
print(zero.float().dtype)

#2nd way
zero=zero.to(torch.float32)
print(zero.dtype)

torch.int64
tensor([0., 0., 0.])
torch.float32
torch.float32


In [45]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
fil= torch.rand(size=(2,3))
fil = torch.fill(fil, 7)
fil

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [51]:
mata= torch.rand(size=(2,2))
print(mata)
matb= torch.rand(size=(2,2))
print(matb)

print(mata+ matb)
print(mata- matb)


tensor([[0.7717, 0.8995],
        [0.8666, 0.4586]])
tensor([[0.2243, 0.8645],
        [0.6220, 0.9524]])
tensor([[0.9960, 1.7640],
        [1.4886, 1.4110]])
tensor([[ 0.5474,  0.0350],
        [ 0.2447, -0.4938]])


In [52]:
mata= torch.rand(size=(3,3))
print(mata)
print(mata*10)


tensor([[0.0526, 0.6242, 0.6880],
        [0.2971, 0.9943, 0.3350],
        [0.4541, 0.9477, 0.8544]])
tensor([[0.5264, 6.2416, 6.8803],
        [2.9710, 9.9429, 3.3504],
        [4.5411, 9.4771, 8.5442]])


In [55]:
_20val =torch.rand(20)
_20val

tensor([0.1833, 0.9280, 0.7891, 0.3309, 0.1898, 0.9297, 0.9750, 0.3806, 0.4388,
        0.4860, 0.5579, 0.5543, 0.9783, 0.8300, 0.2502, 0.7288, 0.4014, 0.8350,
        0.7592, 0.4898])

In [58]:
torch.mean(_20val), torch.std(_20val)

(tensor(0.6008), tensor(0.2680))

In [61]:
mat = torch.rand(size=(4,4))
print(mat)
mat.sum(dim=1)

tensor([[0.8993, 0.6066, 0.7290, 0.7521],
        [0.6500, 0.9423, 0.8231, 0.4448],
        [0.8553, 0.7162, 0.1620, 0.4842],
        [0.4844, 0.1894, 0.7428, 0.4515]])


tensor([2.9870, 2.8603, 2.2177, 1.8681])

In [78]:
rand= torch.rand(12,dtype=float)
print(rand)
a=rand.view((3,4),torch.float32)
print(a)


tensor([0.1043, 0.7083, 0.8184, 0.5468, 0.5227, 0.6684, 0.0129, 0.5920, 0.9457,
        0.1600, 0.3320, 0.7044], dtype=torch.float64)
tensor([[0.1043, 0.7083, 0.8184, 0.5468],
        [0.5227, 0.6684, 0.0129, 0.5920],
        [0.9457, 0.1600, 0.3320, 0.7044]], dtype=torch.float64)


In [79]:
torch.reshape(a,(1,12))

tensor([[0.1043, 0.7083, 0.8184, 0.5468, 0.5227, 0.6684, 0.0129, 0.5920, 0.9457,
         0.1600, 0.3320, 0.7044]], dtype=torch.float64)

In [81]:
rand

tensor([0.1043, 0.7083, 0.8184, 0.5468, 0.5227, 0.6684, 0.0129, 0.5920, 0.9457,
        0.1600, 0.3320, 0.7044], dtype=torch.float64)